### ISSUE TITLE
Question: Is it necessary to generalize over the union of ftvs of type environment and ftvs of constraint?

### ISSUE THREAD

**Issue by bzy-debug** [nrnrnr/build-prove-compare-student-code#14]
Hi, thanks for your great book, but I have a question about one type inference rule of nano-ml.
In the type inference rule of **LET** in nano-ml:
<img width="804" alt="截屏2023-05-18 16 00 53" src="https://github.com/nrnrnr/build-prove-compare-student-code/assets/71200607/19a34b8f-38cf-4dfc-9b24-0903cc02f934">
is $\mbox{ftv}(\Gamma)$ enough for $\mbox{ftv}(\Gamma)\cup\mbox{ftv}(C')$?

According to the definition of free type variables of constraint in [code](https://github.com/nrnrnr/build-prove-compare-student-code/blob/main/bare/nml/ml.sml#LL1594C1-L1594C1):
```sml
fun freetyvarsConstraint (t ~  t') = union (freetyvars t, freetyvars t')
  | freetyvarsConstraint (c /\ c') = union (freetyvarsConstraint c,
                                             freetyvarsConstraint c')
  | freetyvarsConstraint TRIVIAL   = emptyset
```
$\mbox{ftv}(C')=\mbox{dom}\theta \cap \mbox{ftv}(\Gamma)$.
Therefore, $\mbox{ftv}(C') \subseteq \Gamma$, and $\mbox{ftv}(\Gamma)\cup\mbox{ftv}(C') = \mbox{ftv}(\Gamma)$.

If I got anything wrong or misunderstood, please let me know.
Thanks agin for your great book!

**Comment by nrnrnr** [comment]
In the definition of $C'$, only $\alpha$ is limited to the set $\mbox{ftv}(\Gamma)\cup\mbox{ftv}(C')$.  Type $\theta\alpha$ can include a free type variable that is not in this set.

**Comment by bzy-debug** [comment]
That's true, thanks for your answer.
