### ISSUE TITLE
Uncaught exception: LeftAsExercise: type for LAMBDA

### ISSUE THREAD

**Issue by Angeldude** [nrnrnr/build-prove-compare-student-code#17]
Hello, I am attempting to build the source code for the uml interpreter. It builds fine but when I run the binary, this error is produced
```
Uncaught exception:
LeftAsExercise: type for LAMBDA
```

I'm on Windows 10 using WSL2 Ubuntu 24.04.1 LTS 
I'm using Moscow ML 2.10.1 also built from source.

In fact, I get the same error when I try to run any of the ML binaries including Molecule.
I'm not sure if there's anything else I need to do to get it to run properly.

**Comment by Angeldude** [comment]
Sorry for the double post but I think I figured it out. The code is meant to be modified prior to building to get a working interpreter. Is this correct? I'm just trying out the code before I dive into the book but reading through the code that seems to be the case. Please correct me if wrong and if I'm right then this issue can be closed.

**Comment by nrnrnr** [comment]
Yes, you've got it.  You should be able to try out a working interpreter at https://www.build-prove-compare.net/playground/.  Select the language of your choice off to the left.

There are some issues with that app, but it is at least somewhat workable.
