### ISSUE TITLE
Error compiling overflow.c with gcc 12

### ISSUE THREAD

**Issue by MatthewFluet** [nrnrnr/build-prove-compare-student-code#5]
GCC 12 enabled `-Wdangling-pointer` with `-Wall`; such a warning is triggered in `overflow.c` and then promoted to an error by `-Werror`.

```
build-prove-compare/bare/impcore$ gcc --version
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

build-prove-compare/bare/impcore$ make
gcc -std=c11 -pedantic -Wall -Werror -Wextra -Wno-overlength-strings -g  -I. -c overflow.c
overflow.c: In function ‘checkoverflow’:
overflow.c:22:20: error: storing the address of local variable ‘c’ in ‘low_water_mark’ [-Werror=dangling-pointer=]
   22 |     low_water_mark = &c;
      |     ~~~~~~~~~~~~~~~^~~~
overflow.c:13:17: note: ‘c’ declared here
   13 |   volatile char c;
      |                 ^
overflow.c:3:23: note: ‘low_water_mark’ declared here
    3 | static volatile char *low_water_mark = NULL;
      |                       ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:28: overflow.o] Error 1
```

**Comment by nrnrnr** [comment]
> GCC 12 enabled `-Wdangling-pointer` with `-Wall`; such a warning is
 > triggered in `overflow.c` and then promoted to an error by `-Werror`.

I hate this.  Every new gcc version results in breakage.

I don't have gcc 12 to test with, and I can't put
`-Wno-dangling-pointer` because that option is unknown to my gcc.

I haven't updated README, but do try

  make NOWARN=-Wno-dangling-pointer

and please let me know how it goes.

Fresh sources attached.


Norman

**Comment by MatthewFluet** [comment]
Yes, compiling with "-Wno-dangling-pointer" works.  (E-mail attachments seem not to be preserved in GitHub issues; I presume the `NOWARN` was a new Makefile variable included in the fresh sources.)
