### ISSUE TITLE
type error on page 356

### ISSUE THREAD

**Issue by bzy-debug** [nrnrnr/build-prove-compare-student-code#7]
In the second last paragraph illustrating instantiation:

> The instantiation (@ length bool) strips “∀α.” from the front of length’s type, and in what remains, substitutes bool for α. The type of the resulting instance is bool list → bool, or in Typed μScheme, ((list bool) ‐> int).

It seems that the resulting instance should be "bool list → int"

**Comment by nrnrnr** [comment]
Fixed; thanks.
