### ISSUE TITLE
check-expect failure message in uSmalltalk

### ISSUE THREAD

**Issue by MatthewFluet** [nrnrnr/build-prove-compare-student-code#9]
Earlier drafts of PL:BPC used `similar:` for object equality (as opposed to object identity), but the final version uses `=` for object equality and doesn't use the term _similar_.  However, the error message for a failing `check-expect` test uses the term _similar_:
https://github.com/nrnrnr/build-prove-compare-student-code/blob/365a4a61391f510e7a1e6c42c1b1bf1496e3fdfd/bare/usmalltalk/usm.sml#L2695-L2699

**Comment by nrnrnr** [comment]
Thanks for this.

Fixed.
